[package]
name = "LazyTODO"
version = "0.0.0"
edition = "2024"

[dependencies]
color-eyre = "0.6.3"
crossterm = { version = "0.29.0", features = ["event-stream"] }
ratatui = "0.30.2"
sqlite = "*"
tokio = { version = "1.11.0", features = ["full"] }
futures = "0.3.5"
tui = { version = "0.15.0", features = ["crossterm"], default-features = false }
anyhow = "1.0.38"
json = "*"


